apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ops.fanny7d.io/v1beta1",
          "kind": "Apps",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "ops-operator"
            },
            "name": "apps-sample"
          },
          "spec": {
            "image": "nginx:latest",
            "port": 80,
            "replicas": 1
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-12-03T15:56:09Z"
    operators.operatorframework.io/builder: operator-sdk-v1.38.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: ops-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Apps is the Schema for the apps API
      displayName: Apps
      kind: Apps
      name: apps.ops.fanny7d.io
      version: v1beta1
  description: An operator for managing Kubernetes resources including Deployment,
    Service, and Ingress.
  displayName: OPS Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ops.fanny7d.io
          resources:
          - apps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ops.fanny7d.io
          resources:
          - apps/finalizers
          verbs:
          - update
        - apiGroups:
          - ops.fanny7d.io
          resources:
          - apps/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: ops-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: ops-operator
          control-plane: controller-manager
        name: ops-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: fanny7d/ops-operator:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: ops-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: ops-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubernetes
  - operator
  - ops
  - automation
  - deployment
  links:
  - name: Ops Operator
    url: https://ops-operator.domain
  maintainers:
  - email: fanchao1510@outlook.com
    name: fanchao
  maturity: alpha
  provider:
    name: Ops Team
    url: https://github.com/fanny7d/ops-operator
  version: 0.0.1
