apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ops-operator
  name: ops-operator-apps-viewer-role
rules:
- apiGroups:
  - ops.fanny7d.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.fanny7d.io
  resources:
  - apps/status
  verbs:
  - get
