# permissions for end users to view apps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ops-operator
    app.kubernetes.io/managed-by: kustomize
  name: apps-viewer-role
rules:
- apiGroups:
  - ops.fanny7d.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.fanny7d.io
  resources:
  - apps/status
  verbs:
  - get
