apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ops-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Apps is the Schema for the apps API
      displayName: Apps
      kind: Apps
      name: apps.ops.fanny7d.io
      version: v1beta1
  description: An operator for managing Kubernetes resources including Deployment,
    Service, and Ingress.
  displayName: OPS Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubernetes
  - operator
  - ops
  - automation
  - deployment
  links:
  - name: Ops Operator
    url: https://ops-operator.domain
  maintainers:
  - email: fanchao1510@outlook.com
    name: fanchao
  maturity: alpha
  provider:
    name: Ops Team
    url: https://github.com/fanny7d/ops-operator
  version: 0.0.0
